site_name: Rainyel Ramos González
site_url: https://rayniel95.github.io
repo_url: https://github.com/rayniel95
edit_uri: ""

theme:
  name: material
  logo: assets/images/me2.png
  favicon: assets/images/me2.png
 
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - meta
  - toc:
      permalink: 🔗
  
# extra:
#   manifest: manifest.json

nav:
  - Home:
    - Intro: index.md