site_name: Rainyel Ramos González
site_url: https://rayniel95.github.io
repo_url: https://github.com/rayniel95
edit_uri: ""

theme:
  name: material
  logo: assets/images/me2.png
  favicon: assets/images/me2.png
  features:
    - navigation.top
  icon:
    repo: fontawesome/brands/github
    
markdown_extensions:
  - attr_list
  - pymdownx.progressbar
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji
  - meta
  - toc:
      permalink: 🔗
  - abbr
  - extra

plugins:
  - git-revision-date-localized:
      type: date