site_name: Rainyel Ramos González
site_url: https://rayniel95.github.io
repo_url: https://github.com/rayniel95
theme:
  name: material
  logo: assets/images/me.jpg
nav:
  - Home:
    - Intro: index.md